spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop-application
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      format_sql: true
    show-sql: false
  liquibase:
    change-log: classpath:/changeLog.xml
    enabled: true
security:
  client:
    id: ClientId
    secret: secret
  token:
    ttl: 3600
