spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop-application
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:/changeLog.yaml
